# Generated by Django 5.2.7 on 2025-10-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_places_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(choices=[], max_length=1, verbose_name='Номер стола')),
                ('additional_information', models.CharField(blank=True, max_length=500, null=True, verbose_name='Дополнительная информация')),
            ],
        ),
        migrations.DeleteModel(
            name='Places',
        ),
    ]
