# Generated by Django 5.2.7 on 2025-10-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_delete_places'),
        ('workers', '0002_person_remove_workers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='table_number',
            field=models.CharField(choices=[], max_length=1, verbose_name='Стол'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='workers.person')),
            ],
        ),
    ]
