# Generated by Django 5.2.7 on 2025-10-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_table_number_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='table_number',
            field=models.CharField(choices=[], max_length=1, unique=True, verbose_name='Стол'),
        ),
    ]
