# Generated by Django 5.2.7 on 2025-10-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_table_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Занятые места', 'verbose_name_plural': 'Занятые места'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Все места', 'verbose_name_plural': 'Все места'},
        ),
        migrations.AlterField(
            model_name='place',
            name='table_number',
            field=models.CharField(choices=[('1', 'Стол 1'), ('2', 'Стол 2'), ('3', 'Стол 3'), ('4', 'Стол 4'), ('5', 'Стол 5'), ('6', 'Стол 6'), ('7', 'Стол 7'), ('8', 'Стол 8'), ('9', 'Стол 9')], unique=True, verbose_name='Стол'),
        ),
    ]
