# Generated by Django 5.2.7 on 2025-10-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_job_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='table_number',
            field=models.CharField(choices=[('Стол 1', '1'), ('Стол 2', '2'), ('Стол 3', '3'), ('Стол 4', '4'), ('Стол 5', '5'), ('Стол 6', '6'), ('Стол 7', '7'), ('Стол 8', '8'), ('Стол 9', '9')], unique=True, verbose_name='Стол'),
        ),
    ]
