# Generated by Django 5.2.7 on 2025-10-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=3, verbose_name='Пол')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='имя, фамилия, отчество (при наличии)')),
                ('skills', models.CharField(blank=True, max_length=200, null=True, verbose_name='навыки (фронтенд, бэкенд, тестирование, управление проектами и т.д.)')),
                ('skill_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='Уровень освоения навыка')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
        ),
    ]
