# Generated by Django 5.2.7 on 2025-10-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='имя, фамилия, отчество (при наличии)')),
            ],
        ),
        migrations.RemoveField(
            model_name='workers',
            name='name',
        ),
    ]
