# Generated by Django 5.2.7 on 2025-10-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_person_remove_workers_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workers',
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'ITшеики', 'verbose_name_plural': 'ITшеики'},
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='person',
            name='gallery',
            field=models.ImageField(blank=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(max_length=3, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='person',
            name='skill_level',
            field=models.CharField(max_length=20, null=True, verbose_name='Уровень освоения навыка'),
        ),
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.CharField(max_length=200, null=True, verbose_name='навыки (фронтенд, бэкенд, тестирование, управление проектами и т.д.)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='имя, фамилия, отчество (при наличии)'),
        ),
    ]
