# Generated by Django 5.2.7 on 2025-10-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_delete_workers_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('male', 'Муж'), ('female', 'Жен')], null=True, verbose_name='Пол'),
        ),
    ]
