# Generated by Django 5.2.7 on 2025-10-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_person_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'ITшнеики', 'verbose_name_plural': 'ITшнеики'},
        ),
    ]
