# Generated by Django 5.2.7 on 2025-10-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_alter_person_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gallery',
            field=models.ImageField(blank=True, null=True, upload_to='Gallery/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.CharField(max_length=200, null=True, verbose_name='Навыки (фронтенд, бэкенд, тестирование, управление проектами и т.д.)'),
        ),
    ]
