# Generated by Django 5.2.7 on 2025-10-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_alter_person_gallery_alter_person_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО (при наличии)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('male', 'Муж'), ('female', 'Жен')], max_length=6, null=True, verbose_name='Пол'),
        ),
    ]
