# Generated by Django 5.2.7 on 2025-10-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_alter_person_name_alter_person_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'IT-специалисты', 'verbose_name_plural': 'IT-специалисты'},
        ),
        migrations.AlterField(
            model_name='person',
            name='gallery',
            field=models.ImageField(blank=True, null=True, upload_to='Gallery'),
        ),
    ]
