# Generated by Django 5.2.7 on 2025-10-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_alter_person_options_alter_person_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gallery',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
