# Generated by Django 5.2.7 on 2025-10-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_alter_person_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='employment_date',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_on_main',
            field=models.BooleanField(default=False),
        ),
    ]
