# Generated by Django 5.2.7 on 2025-10-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_person_employment_date_person_is_on_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='employment_date',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
