# Generated by Django 5.2.7 on 2025-10-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_alter_person_employment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='employment_date',
        ),
        migrations.AlterField(
            model_name='person',
            name='skill_level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=20, null=True, verbose_name='Уровень освоения навыка'),
        ),
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.CharField(choices=[('fronted', 'фронтенд'), ('beckend', 'бэкенд'), ('testing', 'тестирование'), ('project management', 'управление проектами')], max_length=18, null=True, verbose_name='Навыки'),
        ),
    ]
