# Generated by Django 5.2.7 on 2025-10-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0012_remove_person_employment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='employment_date',
            field=models.TimeField(auto_now=True, verbose_name='Дата принятия на работу'),
        ),
    ]
