# Generated by Django 5.2.7 on 2025-10-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0013_person_employment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='employment_date',
        ),
    ]
