# Generated by Django 5.2.7 on 2025-10-17 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0014_remove_person_employment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='employment',
            field=models.DateField(null=True, verbose_name='Дата трудоустройства'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.desk')),
            ],
        ),
    ]
