# Generated by Django 5.2.7 on 2025-10-20 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0015_desk_person_employment_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desk',
            options={'ordering': ['number'], 'verbose_name': 'Стол', 'verbose_name_plural': 'Столы'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Привязка к столу', 'verbose_name_plural': 'Привязки к столам'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-employment_date'], 'verbose_name': 'IT-специалист', 'verbose_name_plural': 'IT-специалисты'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='employment',
        ),
        migrations.AddField(
            model_name='employee',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.person', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='person',
            name='employment_date',
            field=models.DateField(blank=True, help_text='Дата, когда сотрудник был принят на работу', null=True, verbose_name='Дата приёма на работу'),
        ),
        migrations.AlterField(
            model_name='desk',
            name='number',
            field=models.IntegerField(help_text='Уникальный номер рабочего стола', unique=True, verbose_name='Номер стола'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='desk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.desk', verbose_name='Стол'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительная информация о сотруднике', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gallery',
            field=models.ImageField(blank=True, help_text='Основное фото сотрудника', null=True, upload_to='images/', verbose_name='Фото сотрудника'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_on_main',
            field=models.BooleanField(default=False, help_text='Отметьте, если сотрудник должен отображаться на главной странице', verbose_name='Показывать на главной'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Полное имя сотрудника', max_length=200, null=True, verbose_name='ФИО (при наличии)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='person',
            name='skill_level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True, verbose_name='Уровень освоения навыка'),
        ),
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.CharField(choices=[('frontend', 'Фронтенд'), ('backend', 'Бэкенд'), ('testing', 'Тестирование'), ('project_management', 'Управление проектами')], max_length=50, null=True, verbose_name='Навыки'),
        ),
    ]
