# Generated by Django 5.2.7 on 2025-10-20 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0016_alter_desk_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='desk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='workers.desk', verbose_name='Рабочий стол'),
        ),
    ]
